export interface PartNumberResult {
  model: string;
  storage: string;
  color: string;
}

const PN_DB: Record<string, PartNumberResult> = {
  // iPhone 16 Pro Max
  "MYW33": { model: "iPhone 16 Pro Max", storage: "256GB", color: "Desert Titanium" },
  "MYW43": { model: "iPhone 16 Pro Max", storage: "512GB", color: "Desert Titanium" },
  "MYW53": { model: "iPhone 16 Pro Max", storage: "1TB", color: "Desert Titanium" },
  "MYW63": { model: "iPhone 16 Pro Max", storage: "256GB", color: "Natural Titanium" },
  "MYW73": { model: "iPhone 16 Pro Max", storage: "512GB", color: "Natural Titanium" },
  "MYW83": { model: "iPhone 16 Pro Max", storage: "1TB", color: "Natural Titanium" },
  "MYW93": { model: "iPhone 16 Pro Max", storage: "256GB", color: "White Titanium" },
  "MYWA3": { model: "iPhone 16 Pro Max", storage: "512GB", color: "White Titanium" },
  "MYWD3": { model: "iPhone 16 Pro Max", storage: "1TB", color: "White Titanium" },
  "MYWE3": { model: "iPhone 16 Pro Max", storage: "256GB", color: "Black Titanium" },
  "MYWF3": { model: "iPhone 16 Pro Max", storage: "512GB", color: "Black Titanium" },
  "MYWG3": { model: "iPhone 16 Pro Max", storage: "1TB", color: "Black Titanium" },
  // iPhone 16 Pro
  "MYN63": { model: "iPhone 16 Pro", storage: "128GB", color: "Desert Titanium" },
  "MYN73": { model: "iPhone 16 Pro", storage: "256GB", color: "Desert Titanium" },
  "MYN83": { model: "iPhone 16 Pro", storage: "512GB", color: "Desert Titanium" },
  "MYN93": { model: "iPhone 16 Pro", storage: "1TB", color: "Desert Titanium" },
  "MYNA3": { model: "iPhone 16 Pro", storage: "128GB", color: "Natural Titanium" },
  "MYNC3": { model: "iPhone 16 Pro", storage: "256GB", color: "Natural Titanium" },
  "MYND3": { model: "iPhone 16 Pro", storage: "512GB", color: "Natural Titanium" },
  "MYNE3": { model: "iPhone 16 Pro", storage: "1TB", color: "Natural Titanium" },
  "MYNF3": { model: "iPhone 16 Pro", storage: "128GB", color: "White Titanium" },
  "MYNG3": { model: "iPhone 16 Pro", storage: "256GB", color: "White Titanium" },
  "MYNH3": { model: "iPhone 16 Pro", storage: "512GB", color: "White Titanium" },
  "MYNJ3": { model: "iPhone 16 Pro", storage: "1TB", color: "White Titanium" },
  "MYNK3": { model: "iPhone 16 Pro", storage: "128GB", color: "Black Titanium" },
  "MYNL3": { model: "iPhone 16 Pro", storage: "256GB", color: "Black Titanium" },
  "MYNM3": { model: "iPhone 16 Pro", storage: "512GB", color: "Black Titanium" },
  "MYNN3": { model: "iPhone 16 Pro", storage: "1TB", color: "Black Titanium" },
  // iPhone 16 Plus
  "MYJ23": { model: "iPhone 16 Plus", storage: "128GB", color: "Black" },
  "MYJ33": { model: "iPhone 16 Plus", storage: "256GB", color: "Black" },
  "MYJ43": { model: "iPhone 16 Plus", storage: "512GB", color: "Black" },
  "MYJ53": { model: "iPhone 16 Plus", storage: "128GB", color: "White" },
  "MYJ63": { model: "iPhone 16 Plus", storage: "256GB", color: "White" },
  "MYJ73": { model: "iPhone 16 Plus", storage: "512GB", color: "White" },
  "MYJ83": { model: "iPhone 16 Plus", storage: "128GB", color: "Pink" },
  "MYJ93": { model: "iPhone 16 Plus", storage: "256GB", color: "Pink" },
  "MYJA3": { model: "iPhone 16 Plus", storage: "512GB", color: "Pink" },
  "MYJC3": { model: "iPhone 16 Plus", storage: "128GB", color: "Teal" },
  "MYJD3": { model: "iPhone 16 Plus", storage: "256GB", color: "Teal" },
  "MYJE3": { model: "iPhone 16 Plus", storage: "512GB", color: "Teal" },
  "MYJF3": { model: "iPhone 16 Plus", storage: "128GB", color: "Ultramarine" },
  "MYJG3": { model: "iPhone 16 Plus", storage: "256GB", color: "Ultramarine" },
  "MYJH3": { model: "iPhone 16 Plus", storage: "512GB", color: "Ultramarine" },
  // iPhone 16
  "MYD93": { model: "iPhone 16", storage: "128GB", color: "Black" },
  "MYDA3": { model: "iPhone 16", storage: "256GB", color: "Black" },
  "MYDC3": { model: "iPhone 16", storage: "512GB", color: "Black" },
  "MYDD3": { model: "iPhone 16", storage: "128GB", color: "White" },
  "MYDE3": { model: "iPhone 16", storage: "256GB", color: "White" },
  "MYDF3": { model: "iPhone 16", storage: "512GB", color: "White" },
  "MYDG3": { model: "iPhone 16", storage: "128GB", color: "Pink" },
  "MYDH3": { model: "iPhone 16", storage: "256GB", color: "Pink" },
  "MYDJ3": { model: "iPhone 16", storage: "512GB", color: "Pink" },
  "MYDK3": { model: "iPhone 16", storage: "128GB", color: "Teal" },
  "MYDL3": { model: "iPhone 16", storage: "256GB", color: "Teal" },
  "MYDM3": { model: "iPhone 16", storage: "512GB", color: "Teal" },
  "MYDN3": { model: "iPhone 16", storage: "128GB", color: "Ultramarine" },
  "MYDP3": { model: "iPhone 16", storage: "256GB", color: "Ultramarine" },
  "MYDQ3": { model: "iPhone 16", storage: "512GB", color: "Ultramarine" },
  // iPhone 15 Pro Max
  "MU4F3": { model: "iPhone 15 Pro Max", storage: "256GB", color: "Natural Titanium" },
  "MU4G3": { model: "iPhone 15 Pro Max", storage: "512GB", color: "Natural Titanium" },
  "MU4H3": { model: "iPhone 15 Pro Max", storage: "1TB", color: "Natural Titanium" },
  "MU493": { model: "iPhone 15 Pro Max", storage: "256GB", color: "Blue Titanium" },
  "MU4A3": { model: "iPhone 15 Pro Max", storage: "512GB", color: "Blue Titanium" },
  "MU4D3": { model: "iPhone 15 Pro Max", storage: "1TB", color: "Blue Titanium" },
  "MU4E3": { model: "iPhone 15 Pro Max", storage: "256GB", color: "White Titanium" },
  "MU4J3": { model: "iPhone 15 Pro Max", storage: "512GB", color: "White Titanium" },
  "MU4K3": { model: "iPhone 15 Pro Max", storage: "1TB", color: "White Titanium" },
  "MU4L3": { model: "iPhone 15 Pro Max", storage: "256GB", color: "Black Titanium" },
  "MU4M3": { model: "iPhone 15 Pro Max", storage: "512GB", color: "Black Titanium" },
  "MU4N3": { model: "iPhone 15 Pro Max", storage: "1TB", color: "Black Titanium" },
  // iPhone 15 Pro
  "MU7D3": { model: "iPhone 15 Pro", storage: "128GB", color: "Natural Titanium" },
  "MU7H3": { model: "iPhone 15 Pro", storage: "256GB", color: "Natural Titanium" },
  "MU7M3": { model: "iPhone 15 Pro", storage: "512GB", color: "Natural Titanium" },
  "MU7Q3": { model: "iPhone 15 Pro", storage: "1TB", color: "Natural Titanium" },
  "MU7E3": { model: "iPhone 15 Pro", storage: "128GB", color: "Blue Titanium" },
  "MU7J3": { model: "iPhone 15 Pro", storage: "256GB", color: "Blue Titanium" },
  "MU7N3": { model: "iPhone 15 Pro", storage: "512GB", color: "Blue Titanium" },
  "MU7R3": { model: "iPhone 15 Pro", storage: "1TB", color: "Blue Titanium" },
  "MU7F3": { model: "iPhone 15 Pro", storage: "128GB", color: "White Titanium" },
  "MU7K3": { model: "iPhone 15 Pro", storage: "256GB", color: "White Titanium" },
  "MU7P3": { model: "iPhone 15 Pro", storage: "512GB", color: "White Titanium" },
  "MU7T3": { model: "iPhone 15 Pro", storage: "1TB", color: "White Titanium" },
  "MU7G3": { model: "iPhone 15 Pro", storage: "128GB", color: "Black Titanium" },
  "MU7L3": { model: "iPhone 15 Pro", storage: "256GB", color: "Black Titanium" },
  "MU7U3": { model: "iPhone 15 Pro", storage: "512GB", color: "Black Titanium" },
  "MU7V3": { model: "iPhone 15 Pro", storage: "1TB", color: "Black Titanium" },
  // iPhone 15 Plus
  "MU053": { model: "iPhone 15 Plus", storage: "128GB", color: "Black" },
  "MU063": { model: "iPhone 15 Plus", storage: "256GB", color: "Black" },
  "MU073": { model: "iPhone 15 Plus", storage: "512GB", color: "Black" },
  "MU083": { model: "iPhone 15 Plus", storage: "128GB", color: "Blue" },
  "MU093": { model: "iPhone 15 Plus", storage: "256GB", color: "Blue" },
  "MU0A3": { model: "iPhone 15 Plus", storage: "512GB", color: "Blue" },
  "MU0D3": { model: "iPhone 15 Plus", storage: "128GB", color: "Green" },
  "MU0E3": { model: "iPhone 15 Plus", storage: "256GB", color: "Green" },
  "MU0F3": { model: "iPhone 15 Plus", storage: "512GB", color: "Green" },
  "MU0G3": { model: "iPhone 15 Plus", storage: "128GB", color: "Pink" },
  "MU0H3": { model: "iPhone 15 Plus", storage: "256GB", color: "Pink" },
  "MU0J3": { model: "iPhone 15 Plus", storage: "512GB", color: "Pink" },
  "MU0K3": { model: "iPhone 15 Plus", storage: "128GB", color: "Yellow" },
  "MU0L3": { model: "iPhone 15 Plus", storage: "256GB", color: "Yellow" },
  "MU0M3": { model: "iPhone 15 Plus", storage: "512GB", color: "Yellow" },
  // iPhone 15
  "MU153": { model: "iPhone 15", storage: "128GB", color: "Black" },
  "MU163": { model: "iPhone 15", storage: "256GB", color: "Black" },
  "MU173": { model: "iPhone 15", storage: "512GB", color: "Black" },
  "MU183": { model: "iPhone 15", storage: "128GB", color: "Blue" },
  "MU193": { model: "iPhone 15", storage: "256GB", color: "Blue" },
  "MU1A3": { model: "iPhone 15", storage: "512GB", color: "Blue" },
  "MU1D3": { model: "iPhone 15", storage: "128GB", color: "Green" },
  "MU1E3": { model: "iPhone 15", storage: "256GB", color: "Green" },
  "MU1F3": { model: "iPhone 15", storage: "512GB", color: "Green" },
  "MU1G3": { model: "iPhone 15", storage: "128GB", color: "Pink" },
  "MU1H3": { model: "iPhone 15", storage: "256GB", color: "Pink" },
  "MU1J3": { model: "iPhone 15", storage: "512GB", color: "Pink" },
  "MU1K3": { model: "iPhone 15", storage: "128GB", color: "Yellow" },
  "MU1L3": { model: "iPhone 15", storage: "256GB", color: "Yellow" },
  "MU1M3": { model: "iPhone 15", storage: "512GB", color: "Yellow" },
  // iPhone 14 Pro Max
  "MQ8R3": { model: "iPhone 14 Pro Max", storage: "128GB", color: "Space Black" },
  "MQ8T3": { model: "iPhone 14 Pro Max", storage: "256GB", color: "Space Black" },
  "MQ8U3": { model: "iPhone 14 Pro Max", storage: "512GB", color: "Space Black" },
  "MQ8V3": { model: "iPhone 14 Pro Max", storage: "1TB", color: "Space Black" },
  "MQ863": { model: "iPhone 14 Pro Max", storage: "128GB", color: "Deep Purple" },
  "MQ873": { model: "iPhone 14 Pro Max", storage: "256GB", color: "Deep Purple" },
  "MQ883": { model: "iPhone 14 Pro Max", storage: "512GB", color: "Deep Purple" },
  "MQ893": { model: "iPhone 14 Pro Max", storage: "1TB", color: "Deep Purple" },
  "MQ8A3": { model: "iPhone 14 Pro Max", storage: "128GB", color: "Gold" },
  "MQ8D3": { model: "iPhone 14 Pro Max", storage: "256GB", color: "Gold" },
  "MQ8E3": { model: "iPhone 14 Pro Max", storage: "512GB", color: "Gold" },
  "MQ8F3": { model: "iPhone 14 Pro Max", storage: "1TB", color: "Gold" },
  "MQ8G3": { model: "iPhone 14 Pro Max", storage: "128GB", color: "Silver" },
  "MQ8H3": { model: "iPhone 14 Pro Max", storage: "256GB", color: "Silver" },
  "MQ8J3": { model: "iPhone 14 Pro Max", storage: "512GB", color: "Silver" },
  "MQ8K3": { model: "iPhone 14 Pro Max", storage: "1TB", color: "Silver" },
  // iPhone 14 Pro
  "MQ0E3": { model: "iPhone 14 Pro", storage: "128GB", color: "Space Black" },
  "MQ0F3": { model: "iPhone 14 Pro", storage: "256GB", color: "Space Black" },
  "MQ0G3": { model: "iPhone 14 Pro", storage: "512GB", color: "Space Black" },
  "MQ0H3": { model: "iPhone 14 Pro", storage: "1TB", color: "Space Black" },
  "MQ003": { model: "iPhone 14 Pro", storage: "128GB", color: "Deep Purple" },
  "MQ013": { model: "iPhone 14 Pro", storage: "256GB", color: "Deep Purple" },
  "MQ023": { model: "iPhone 14 Pro", storage: "512GB", color: "Deep Purple" },
  "MQ033": { model: "iPhone 14 Pro", storage: "1TB", color: "Deep Purple" },
  "MQ043": { model: "iPhone 14 Pro", storage: "128GB", color: "Gold" },
  "MQ053": { model: "iPhone 14 Pro", storage: "256GB", color: "Gold" },
  "MQ063": { model: "iPhone 14 Pro", storage: "512GB", color: "Gold" },
  "MQ073": { model: "iPhone 14 Pro", storage: "1TB", color: "Gold" },
  "MQ083": { model: "iPhone 14 Pro", storage: "128GB", color: "Silver" },
  "MQ093": { model: "iPhone 14 Pro", storage: "256GB", color: "Silver" },
  "MQ0A3": { model: "iPhone 14 Pro", storage: "512GB", color: "Silver" },
  "MQ0D3": { model: "iPhone 14 Pro", storage: "1TB", color: "Silver" },
  // iPhone 14 Plus
  "MQ4T3": { model: "iPhone 14 Plus", storage: "128GB", color: "Midnight" },
  "MQ4U3": { model: "iPhone 14 Plus", storage: "256GB", color: "Midnight" },
  "MQ4V3": { model: "iPhone 14 Plus", storage: "512GB", color: "Midnight" },
  "MQ4X3": { model: "iPhone 14 Plus", storage: "128GB", color: "Starlight" },
  "MQ503": { model: "iPhone 14 Plus", storage: "256GB", color: "Starlight" },
  "MQ513": { model: "iPhone 14 Plus", storage: "512GB", color: "Starlight" },
  "MQ523": { model: "iPhone 14 Plus", storage: "128GB", color: "Blue" },
  "MQ533": { model: "iPhone 14 Plus", storage: "256GB", color: "Blue" },
  "MQ543": { model: "iPhone 14 Plus", storage: "512GB", color: "Blue" },
  "MQ553": { model: "iPhone 14 Plus", storage: "128GB", color: "Purple" },
  "MQ563": { model: "iPhone 14 Plus", storage: "256GB", color: "Purple" },
  "MQ573": { model: "iPhone 14 Plus", storage: "512GB", color: "Purple" },
  "MQ583": { model: "iPhone 14 Plus", storage: "128GB", color: "Red" },
  "MQ593": { model: "iPhone 14 Plus", storage: "256GB", color: "Red" },
  "MQ5A3": { model: "iPhone 14 Plus", storage: "512GB", color: "Red" },
  // iPhone 14
  "MPWP3": { model: "iPhone 14", storage: "128GB", color: "Midnight" },
  "MPWQ3": { model: "iPhone 14", storage: "256GB", color: "Midnight" },
  "MPWR3": { model: "iPhone 14", storage: "512GB", color: "Midnight" },
  "MPX83": { model: "iPhone 14", storage: "128GB", color: "Starlight" },
  "MPX93": { model: "iPhone 14", storage: "256GB", color: "Starlight" },
  "MPXA3": { model: "iPhone 14", storage: "512GB", color: "Starlight" },
  "MPXD3": { model: "iPhone 14", storage: "128GB", color: "Blue" },
  "MPXE3": { model: "iPhone 14", storage: "256GB", color: "Blue" },
  "MPXF3": { model: "iPhone 14", storage: "512GB", color: "Blue" },
  "MPXG3": { model: "iPhone 14", storage: "128GB", color: "Purple" },
  "MPXH3": { model: "iPhone 14", storage: "256GB", color: "Purple" },
  "MPXJ3": { model: "iPhone 14", storage: "512GB", color: "Purple" },
  "MPXK3": { model: "iPhone 14", storage: "128GB", color: "Red" },
  "MPXL3": { model: "iPhone 14", storage: "256GB", color: "Red" },
  "MPXM3": { model: "iPhone 14", storage: "512GB", color: "Red" },
  // iPhone 13 Pro Max
  "MLK63": { model: "iPhone 13 Pro Max", storage: "128GB", color: "Graphite" },
  "MLK73": { model: "iPhone 13 Pro Max", storage: "256GB", color: "Graphite" },
  "MLK83": { model: "iPhone 13 Pro Max", storage: "512GB", color: "Graphite" },
  "MLK93": { model: "iPhone 13 Pro Max", storage: "1TB", color: "Graphite" },
  "MLKA3": { model: "iPhone 13 Pro Max", storage: "128GB", color: "Gold" },
  "MLKC3": { model: "iPhone 13 Pro Max", storage: "256GB", color: "Gold" },
  "MLKD3": { model: "iPhone 13 Pro Max", storage: "512GB", color: "Gold" },
  "MLKE3": { model: "iPhone 13 Pro Max", storage: "1TB", color: "Gold" },
  "MLKF3": { model: "iPhone 13 Pro Max", storage: "128GB", color: "Sierra Blue" },
  "MLKG3": { model: "iPhone 13 Pro Max", storage: "256GB", color: "Sierra Blue" },
  "MLKH3": { model: "iPhone 13 Pro Max", storage: "512GB", color: "Sierra Blue" },
  "MLKJ3": { model: "iPhone 13 Pro Max", storage: "1TB", color: "Sierra Blue" },
  "MLKK3": { model: "iPhone 13 Pro Max", storage: "128GB", color: "Silver" },
  "MLKL3": { model: "iPhone 13 Pro Max", storage: "256GB", color: "Silver" },
  "MLKM3": { model: "iPhone 13 Pro Max", storage: "512GB", color: "Silver" },
  "MLKN3": { model: "iPhone 13 Pro Max", storage: "1TB", color: "Silver" },
  // iPhone 13 Pro
  "MLV93": { model: "iPhone 13 Pro", storage: "128GB", color: "Graphite" },
  "MLVA3": { model: "iPhone 13 Pro", storage: "256GB", color: "Graphite" },
  "MLVC3": { model: "iPhone 13 Pro", storage: "512GB", color: "Graphite" },
  "MLVD3": { model: "iPhone 13 Pro", storage: "1TB", color: "Graphite" },
  "MLVE3": { model: "iPhone 13 Pro", storage: "128GB", color: "Gold" },
  "MLVF3": { model: "iPhone 13 Pro", storage: "256GB", color: "Gold" },
  "MLVG3": { model: "iPhone 13 Pro", storage: "512GB", color: "Gold" },
  "MLVH3": { model: "iPhone 13 Pro", storage: "1TB", color: "Gold" },
  "MLVJ3": { model: "iPhone 13 Pro", storage: "128GB", color: "Sierra Blue" },
  "MLVK3": { model: "iPhone 13 Pro", storage: "256GB", color: "Sierra Blue" },
  "MLVL3": { model: "iPhone 13 Pro", storage: "512GB", color: "Sierra Blue" },
  "MLVM3": { model: "iPhone 13 Pro", storage: "1TB", color: "Sierra Blue" },
  "MLVN3": { model: "iPhone 13 Pro", storage: "128GB", color: "Silver" },
  "MLVP3": { model: "iPhone 13 Pro", storage: "256GB", color: "Silver" },
  "MLVQ3": { model: "iPhone 13 Pro", storage: "512GB", color: "Silver" },
  "MLVR3": { model: "iPhone 13 Pro", storage: "1TB", color: "Silver" },
  // iPhone 13
  "MLPF3": { model: "iPhone 13", storage: "128GB", color: "Midnight" },
  "MLPG3": { model: "iPhone 13", storage: "256GB", color: "Midnight" },
  "MLPH3": { model: "iPhone 13", storage: "512GB", color: "Midnight" },
  "MLPK3": { model: "iPhone 13", storage: "128GB", color: "Starlight" },
  "MLPL3": { model: "iPhone 13", storage: "256GB", color: "Starlight" },
  "MLPM3": { model: "iPhone 13", storage: "512GB", color: "Starlight" },
  "MLPN3": { model: "iPhone 13", storage: "128GB", color: "Blue" },
  "MLPQ3": { model: "iPhone 13", storage: "256GB", color: "Blue" },
  "MLPR3": { model: "iPhone 13", storage: "512GB", color: "Blue" },
  "MLPT3": { model: "iPhone 13", storage: "128GB", color: "Pink" },
  "MLPU3": { model: "iPhone 13", storage: "256GB", color: "Pink" },
  "MLPV3": { model: "iPhone 13", storage: "512GB", color: "Pink" },
  "MLPW3": { model: "iPhone 13", storage: "128GB", color: "Red" },
  "MLPX3": { model: "iPhone 13", storage: "256GB", color: "Red" },
  "MLPY3": { model: "iPhone 13", storage: "512GB", color: "Red" },
  // iPhone 13 mini
  "MLA23": { model: "iPhone 13 mini", storage: "128GB", color: "Midnight" },
  "MLA33": { model: "iPhone 13 mini", storage: "256GB", color: "Midnight" },
  "MLA43": { model: "iPhone 13 mini", storage: "512GB", color: "Midnight" },
  "MLA53": { model: "iPhone 13 mini", storage: "128GB", color: "Starlight" },
  "MLA63": { model: "iPhone 13 mini", storage: "256GB", color: "Starlight" },
  "MLA73": { model: "iPhone 13 mini", storage: "512GB", color: "Starlight" },
  "MLA83": { model: "iPhone 13 mini", storage: "128GB", color: "Blue" },
  "MLA93": { model: "iPhone 13 mini", storage: "256GB", color: "Blue" },
  "MLAA3": { model: "iPhone 13 mini", storage: "512GB", color: "Blue" },
  "MLAC3": { model: "iPhone 13 mini", storage: "128GB", color: "Pink" },
  "MLAD3": { model: "iPhone 13 mini", storage: "256GB", color: "Pink" },
  "MLAE3": { model: "iPhone 13 mini", storage: "512GB", color: "Pink" },
  "MLAF3": { model: "iPhone 13 mini", storage: "128GB", color: "Red" },
  "MLAG3": { model: "iPhone 13 mini", storage: "256GB", color: "Red" },
  "MLAH3": { model: "iPhone 13 mini", storage: "512GB", color: "Red" },
  // iPhone SE (3rd gen, 2022)
  "MMX63": { model: "iPhone SE (3rd gen)", storage: "64GB", color: "Midnight" },
  "MMX73": { model: "iPhone SE (3rd gen)", storage: "128GB", color: "Midnight" },
  "MMX83": { model: "iPhone SE (3rd gen)", storage: "256GB", color: "Midnight" },
  "MMX93": { model: "iPhone SE (3rd gen)", storage: "64GB", color: "Starlight" },
  "MMXA3": { model: "iPhone SE (3rd gen)", storage: "128GB", color: "Starlight" },
  "MMXC3": { model: "iPhone SE (3rd gen)", storage: "256GB", color: "Starlight" },
  "MMXD3": { model: "iPhone SE (3rd gen)", storage: "64GB", color: "Red" },
  "MMXE3": { model: "iPhone SE (3rd gen)", storage: "128GB", color: "Red" },
  "MMXF3": { model: "iPhone SE (3rd gen)", storage: "256GB", color: "Red" },
  // iPhone 12 Pro Max
  "MGDM3": { model: "iPhone 12 Pro Max", storage: "128GB", color: "Graphite" },
  "MGDN3": { model: "iPhone 12 Pro Max", storage: "256GB", color: "Graphite" },
  "MGDP3": { model: "iPhone 12 Pro Max", storage: "512GB", color: "Graphite" },
  "MGDQ3": { model: "iPhone 12 Pro Max", storage: "128GB", color: "Gold" },
  "MGDR3": { model: "iPhone 12 Pro Max", storage: "256GB", color: "Gold" },
  "MGDT3": { model: "iPhone 12 Pro Max", storage: "512GB", color: "Gold" },
  "MGDW3": { model: "iPhone 12 Pro Max", storage: "128GB", color: "Pacific Blue" },
  "MGDX3": { model: "iPhone 12 Pro Max", storage: "256GB", color: "Pacific Blue" },
  "MGDY3": { model: "iPhone 12 Pro Max", storage: "512GB", color: "Pacific Blue" },
  "MGE03": { model: "iPhone 12 Pro Max", storage: "128GB", color: "Silver" },
  "MGE13": { model: "iPhone 12 Pro Max", storage: "256GB", color: "Silver" },
  "MGE23": { model: "iPhone 12 Pro Max", storage: "512GB", color: "Silver" },
  // iPhone 12 Pro
  "MGLH3": { model: "iPhone 12 Pro", storage: "128GB", color: "Graphite" },
  "MGLJ3": { model: "iPhone 12 Pro", storage: "256GB", color: "Graphite" },
  "MGLK3": { model: "iPhone 12 Pro", storage: "512GB", color: "Graphite" },
  "MGLL3": { model: "iPhone 12 Pro", storage: "128GB", color: "Gold" },
  "MGLM3": { model: "iPhone 12 Pro", storage: "256GB", color: "Gold" },
  "MGLN3": { model: "iPhone 12 Pro", storage: "512GB", color: "Gold" },
  "MGLP3": { model: "iPhone 12 Pro", storage: "128GB", color: "Pacific Blue" },
  "MGLQ3": { model: "iPhone 12 Pro", storage: "256GB", color: "Pacific Blue" },
  "MGLR3": { model: "iPhone 12 Pro", storage: "512GB", color: "Pacific Blue" },
  "MGLT3": { model: "iPhone 12 Pro", storage: "128GB", color: "Silver" },
  "MGLU3": { model: "iPhone 12 Pro", storage: "256GB", color: "Silver" },
  "MGLV3": { model: "iPhone 12 Pro", storage: "512GB", color: "Silver" },
  // iPhone 12
  "MGJ93": { model: "iPhone 12", storage: "64GB", color: "Black" },
  "MGJA3": { model: "iPhone 12", storage: "128GB", color: "Black" },
  "MGJC3": { model: "iPhone 12", storage: "256GB", color: "Black" },
  "MGJE3": { model: "iPhone 12", storage: "64GB", color: "White" },
  "MGJF3": { model: "iPhone 12", storage: "128GB", color: "White" },
  "MGJG3": { model: "iPhone 12", storage: "256GB", color: "White" },
  "MGJH3": { model: "iPhone 12", storage: "64GB", color: "Blue" },
  "MGJJ3": { model: "iPhone 12", storage: "128GB", color: "Blue" },
  "MGJK3": { model: "iPhone 12", storage: "256GB", color: "Blue" },
  "MGJL3": { model: "iPhone 12", storage: "64GB", color: "Green" },
  "MGJM3": { model: "iPhone 12", storage: "128GB", color: "Green" },
  "MGJN3": { model: "iPhone 12", storage: "256GB", color: "Green" },
  "MGJP3": { model: "iPhone 12", storage: "64GB", color: "Red" },
  "MGJQ3": { model: "iPhone 12", storage: "128GB", color: "Red" },
  "MGJR3": { model: "iPhone 12", storage: "256GB", color: "Red" },
  // iPhone 12 mini
  "MGE73": { model: "iPhone 12 mini", storage: "64GB", color: "Black" },
  "MGE83": { model: "iPhone 12 mini", storage: "128GB", color: "Black" },
  "MGE93": { model: "iPhone 12 mini", storage: "256GB", color: "Black" },
  "MGEA3": { model: "iPhone 12 mini", storage: "64GB", color: "White" },
  "MGEC3": { model: "iPhone 12 mini", storage: "128GB", color: "White" },
  "MGED3": { model: "iPhone 12 mini", storage: "256GB", color: "White" },
  "MGEE3": { model: "iPhone 12 mini", storage: "64GB", color: "Blue" },
  "MGEF3": { model: "iPhone 12 mini", storage: "128GB", color: "Blue" },
  "MGEG3": { model: "iPhone 12 mini", storage: "256GB", color: "Blue" },
  "MGEH3": { model: "iPhone 12 mini", storage: "64GB", color: "Green" },
  "MGEJ3": { model: "iPhone 12 mini", storage: "128GB", color: "Green" },
  "MGEK3": { model: "iPhone 12 mini", storage: "256GB", color: "Green" },
  "MGEL3": { model: "iPhone 12 mini", storage: "64GB", color: "Red" },
  "MGEM3": { model: "iPhone 12 mini", storage: "128GB", color: "Red" },
  "MGEN3": { model: "iPhone 12 mini", storage: "256GB", color: "Red" },
};

export function lookupByPartNumber(raw: string): PartNumberResult | null {
  const clean = raw.trim().toUpperCase().replace(/\/[A-Z]$/, "");
  const key5 = clean.slice(0, 5);
  return PN_DB[key5] ?? null;
}
